import type { Metadata } from "next";
import { Geist, Geist_Mono,Barlow } from "next/font/google";
import "./globals.css";

//fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const barlowFont = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

//metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${barlowFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
